ulauncher/config.py
Currently inotify watch is added to each xdg data dir like `/usr/share` and recursively adds every directory running out of user watches and spamming logs hundreds of error messages like this
```
ERROR | pyinotify: add_watch() | add_watch: cannot watch /usr/share/icu WD=-1, Errno=No space left on device (ENOSPC)
```
While one fix is to increase user watches same as in #51 after looking over the code it became clear that the watch should be done on the `applications/` folder for each XDG data dir as per XDG spec: https://specifications.freedesktop.org/menu-spec/latest/ar01s02.html.
> $XDG_DATA_DIRS/applications/
>
> This directory contains a .desktop file for each possible menu item. Each directory in the $XDG_DATA_DIRS search path should be used (i.e. desktop entries are collected from …
=> fix inode flood (update DESKTOP_DIRS to be filled with <data-dir>/applications)

tests/search/apps/test_AppDb.py, ulauncher/search/apps/AppDb.py, ulauncher/util/desktop/reader.py
This fix addresses 2 related situations. Both fixes are needed to help Ulauncher find .desktop folders in the same way as XDG spec defines it.
Fix 1:
Dedup the scanned .desktop files following the XDG spec where only the .desktop file found in the first XDG_DATA_DIR paths is the one we use. This is not happening currently and files located in the $HOME/.local/share/applications were not found/prefered in some scenarios where they file in /usr/share or other folder were either found first or updated on user watch (i.e. upgrade of software). Specific issue encountered is that I had copied and modified a specific desktop file from `/usr/share/applications` to `~/.local/share/applications` but it was not  prefered.
Changes for this fix are only in util/desktop/reader.py
To clarify with an …
=> Comply with XDG spec on .desktop location, dedup .desktop search per XDG_DATA_DIR and fix search to not collapse same Name

data/preferences/src/components/pages/ExtensionConfig.vue
I'm not a grammar expert, but I'm pretty sure Title Case should only be used in headings and in texts for names, products or companies (like "Pulp Fiction" or "America Online"). The keyword preferences capitalizes the word "Keyword", which looks quirky to me. Some keywords are lowercased too, making the labels "npm Keyword" or "md5 Keyword".
Before (with lowercased keywords)
After (with Title Cased keyword)
=> Lowercase 'Keyword' in extensions preferences pane

build-utils/build-deb.sh, build-utils/build-doc.sh, build-utils/build-preferences.sh, build-utils/build-rpm.sh, build-utils/build-targz.sh, build-utils/create-build-images.sh, build-utils/dev-container.sh, build-utils/extract-launchpad-ssh.sh, build-utils/functions.sh, build-utils/release.sh, build-utils/send-sighup.sh, build-utils/travis-cli-container.sh, build-utils/travis-test.sh, build-utils/watch-doc.sh, dev-clean.sh, dev-nkpy.sh, dev-run.sh, glade, setup.py, test
Hi @gornostal,
This PR has changes I found helped me develop. Each category of change is broken up in individual commit in case you only like some. If you do not like any, I understand, I'll sidecar them for my own development. The changes are:
1. Change all bash sheebangs from '#!/bin/bash` to '#!/usr/bin/env bash'
**Rationale:** not all linux systems have /bin/bash and common practice to fix this is to use /usr/bin/env
2. Added dev-clean.sh and dev-nkpy.sh
**Rationale:**
dev-clean.sh removes the files installed by dev-run.sh, which means that system level working ulauncher can now be used.
dev-nkpy.sh is useful to remove pyc/pyo and __pycache__ folder. This ESPECIALLY helps when the pyc files are generated inside the docker container during the test run and end up being owned by …
=> Development toolchain cleanup

ulauncher/ui/windows/UlauncherWindow.py
#349 #205
On LXDE Ubuntu 18.04 with i3-gaps, I was consistently having an issue with the window jumping all over the place.   The location would be correct on a fresh launch, then wrong every time after that.
I traced the issue to [the Python gtk.Window docs](https://developer.gnome.org/pygtk/stable/class-gtkwindow.html#move)
> The move() method asks the window manager to move the window to the position specified by x and y. Window managers are free to ignore this. In fact, most window managers ignore requests for initial window positions (instead using a user-defined placement algorithm) and honor requests after the window has already been shown.
As far as I can tell, my window manager (and most of them) are ignoring the request for initial position before the window is presented. I made …
=> Make window visible before requesting move.

docs/extensions/tutorial.rst, ulauncher/config.py, ulauncher/main.py, ulauncher/search/QueryHistoryDb.py, ulauncher/search/apps/AppStatDb.py, ulauncher/utils/setup_logging.py
#152, #347
Implement #347.
> A cache [...] stores data so future requests for that data can be served faster [...]. — https://en.wikipedia.org/wiki/Cache_(computing)
These existing uses of `CACHE_DIR` record history, so they should not be considered cache:
- QueryHistoryDb
- AppStatDb
- Logging
I've also made it so that extensions are saved in `DATA_DIR` (the new variable pointing to `xdg-data-home`). While extensions can be "recomputed" (i.e. downloaded again), it takes a relatively long time to download them, and not too much space to store them persistently. This is in fact what bit me initially: I made my system clear the cache on shut down because I don't care about a cache from the previous session, but with Ulauncher extensions being treated as cache I'd have to wait an …
=> Treat some data as persistent and save them in XDG_DATA_HOME

data/preferences/package.json, data/preferences/src/components/pages/Shortcuts.vue, data/preferences/yarn.lock
Fixes https://github.com/Ulauncher/Ulauncher/issues/383
Regression introduced in `bootstrap-vue@2.0.0-rc.11`, that causes cursor to move to the end of input after input event, has been fixed in newer versions.
This updates `bootstrap-vue` package to the latest stable version, along with changes to match the API  of `b-table` component from this package: new slot naming convention and format to pass table fields.
Vue.js is also updated to the latest version, as recommended for the package.
Arch Linux
Kernel version 5.3.1
Gnome 3.34
P.S. Thanks for the cool project! :smile:
=> Update bootstrap-vue package

ulauncher/main.py
When `from gi.repository import Gtk` is called before `gi.require_version('Gtk', '3.0')`, the latter has no effect and Gtk version is not ensured, as evidenced by the message
```
/usr/lib/python3/dist-packages/ulauncher/main.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gtk
```
This tiny PR fixes that.
This doesn't really matter, but it's
```
Distributor ID:	elementary
Description:	elementary OS 5.0 Juno
Release:	5.0
Codename:	juno
```
=> Move gi.require_version() to the proper place

tests/search/apps/test_app_watcher.py, ulauncher/search/apps/app_watcher.py, ulauncher/utils/desktop/reader.py
Currently when some.desktop file exists in more then one XDG_DIR and one of them is updated (for example via apt-get upgrade installing new version) the some.desktop file is added to the database. This PR prevents this by checing if the updated some.desktop is in the path in the superceded XDG directory. This avoid duplicates.
A more specific case I encountered was when I had a $HOME/.local/share/applications/some.desktop hiding a desktop entry in /usr/share/applications/some.desktop ... upon upgrade of the package containing some.desktop the hidden entry would be shown
Ubuntu 18.04.3
=> Skip adding some.desktop file in the database if it is superceded by it's counterpart in XDG_DIRS

data/preferences/src/components/pages/Preferences.vue, ulauncher/api/shared/action/LaunchAppAction.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/util/Settings.py
See #295 
@goodwillcoding suggested auto-detecting *could* be possible. I don't think it is, but I may have missed something. The `TERM`-variable is not for this and the dconf entries are deprecated. So even if I could use them I think that would be making matters worse.
Either way, I made it into a setting "terminal-exec", which is added to the advanced section of the preferences window as "Terminal Launch Command" (not thrilled about the name but I needed to fine one that implied that the exec argument should be included).
It updates with the "change"-event, so when the focus is lost after having changed, rather than when it actually changes.
The exec flag is usually `-e` or `-x` it seems (with somewhat different meanings). For gnome-terminal it's `--` though.
=> Add default terminal setting for desktop entries

ulauncher/config.py
n/a
Wayland sessions typically do not set `GDK_BACKEND` to anything - not even gnome. The reason for this is that it forces GDK apps to use wayland, but also any other GDK apps launched from it which might break in unexpected ways. GTK auto selects the right backend instead. This is why firefox recommends using `MOZ_ENABLE_WAYLAND` for instance.
Tweak the wayland detector accordingly.
Ubuntu 19.10, Gnome (wayland / x11), Sway 1.4, Mate 1.22 (x11)
=> Fix: GDK_BACKEND is not a reliable indicator of a wayland session

ulauncher/utils/Theme.py
I added one line of code to ensure that themes copied to ~/.cache/ulauncher_cache/themes have the correct file permissions. This fixes issues with package managers with read-only stores such as NixOS (https://github.com/NixOS/nixpkgs/pull/81207).
NixOS, i3 with no desktop environment.
=> Ensure correct theme file permissions

ulauncher/search/apps/AppDb.py
This pull request resolves #510.
If a .desktop file doesn't have the `Comment` field, the `GenericName` field's value will be used to set description for an application record, unless it's the same as the `Name` field's value.
Kubuntu 19.10
KDE Plasma 5.17.5
=> Fall back to GenericName field if Comment field is missing

tests/search/apps/test_AppDb.py, ulauncher/search/apps/AppDb.py
Reverts Ulauncher/Ulauncher#516 in order to fix a regression bug: #542, #545, #544
=> Revert "Add app descriptions to search"

scripts/make-release.sh
n/a
Add build for upcoming Ubuntu Groovy (20.10)
Tested new build via repo'sdocker image
```
~ docker run --rm -it ulauncher-build bash
root@f9f5031f9124:/workdir# RELEASE=groovy ./ul build-deb 5.8.2-a1 --deb
Building DEB package for Ulauncher 5.8.2-a1...
➜ Checking that current version is not in debian/changelog
➜ Building Preferences UI
✔ Preferences are already built. Skipping.
➜ Copying src to a temp dir
➜ Building deb package
dpkg-buildpackage: info: source package ulauncher
dpkg-buildpackage: info: source version 5.8.2-a1
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Aleksandr Gornostal <ulauncher.app@gmail.com>
dpkg-buildpackage: info: host architecture amd64
[...]
dpkg-buildpackage: info: full upload; Debian-native package (full …
```
=> Add Ubuntu groovy (20.10) ppa build

README.md, contrib/systemd/ulauncher.service
This is useful for users who have systemd and want to run `ulauncher` that way.
Documentation was updated accordingly.
For users running `systemd` it's a lot cleaner to run `ulauncher` from a dedicated unit file (logging, restarting, stopping, ...) than through a raw binary.
This is for package maintainers mostly. If this gets merged, I can help make the proper changes in [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ulauncher) on Arch for example.
=> Add ulauncher systemd unit file

data/preferences/src/api/fixture.js, data/preferences/src/components/pages/Preferences.vue, scripts/common.sh, scripts/dev-container.sh, scripts/tests.sh, tests/ui/windows/test_PreferencesUlauncherDialog.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/Settings.py
Addresses #337.
Also address #638.
This add a user preference option which will prevent ULauncher from closing when focus is lost because of the mouse. This makes ULauncher compatible with focus follows mouse and sloppy focus modes.
The issue talked about making this option as a CLI command. However, that makes it more challenging to set the preference for the user if they are using a system installed ULauncher. In that case they would have to modify the desktop file to add the shortcut, and the modification would likely get overridden on the next update. I was able to make this a user preference so that the customization is stored in the preferences file.
I tried to make the UI element short and meaningful about what it did and not how it was implemented. Internally the option is …
=> Add option to not hide when losing focus due to the mouse

ulauncher/search/calc/CalcMode.py
Solves #623 
A very minor change, now the caret operator will be used as a pow operator instead of an XOR operator.
=> Caret now is used as a pow operator instead of XOR in CalcMode

ulauncher/utils/db/KeyValueJsonDb.py
One json file got corrupted and the application is no more working... Happening mainly with `shortcuts.json`
https://github.com/Ulauncher/Ulauncher/issues/592
https://github.com/Ulauncher/Ulauncher/issues/621
https://github.com/Ulauncher/Ulauncher/issues/592
If the file is not a valid json, write default records `{}`.
Ubuntu, gnome, last version
=> Fix json files corruptions

ulauncher/api/server/DeferredResultRenderer.py, ulauncher/api/shared/action/CopyToClipboardAction.py, ulauncher/api/shared/action/RenderResultListAction.py, ulauncher/api/shared/action/SetUserQueryAction.py, ulauncher/search/file_browser/FileBrowserMode.py, ulauncher/ui/AppIndicator.py, ulauncher/ui/ResultItemWidget.py, ulauncher/ui/windows/Builder.py, ulauncher/ui/windows/HotkeyDialog.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/ui/windows/WindowHelper.py, ulauncher/utils/Settings.py, ulauncher/utils/decorator/glib_idle_add.py, ulauncher/utils/desktop/reader.py, ulauncher/utils/display.py, ulauncher/utils/image_loader.py, ulauncher/utils/version_cmp.py
#703 
There are some usages of Gnome libraries in various modules which do not specify a specific version. Now that systems are starting to ship with Gtk4 installed, this means that Gtk4 is picked by default. Not only might this version change cause generally surprising behavior, but if an extension then later tries to explicitly call out the Gtk3 libraries there is an exception, since the Gtk4 libraries are already loaded.
Technically it looks like all the is needed to address #703 is to do the explicit import in the `utils/display.py`, at least with the extensions I tested with. However, the same situation can happen if an extension inherited ANY of the modules lacking the explicit version call out, so I thought it was useful to just set them all now. I specifically did not set them in …
=> Explicitly import versions for all Gnome related libraries.

tests/conftest.py
This fixes the tests when running with GTK4.
Before this PR they all say says `gi.RepositoryError: Requiring namespace 'Gdk' version '3.0', but '4.0' is already loaded`
Credit to @troycurtisjr
=> Explicitly import GdkX11 3.0 in tests.

README.md, scripts/build-targz.sh, ulauncher.service
Make systemd service file able to auto-start more consistently and include in the source tarball.
Currently the arch, deb, and rpms builds do not automatically include this file, but I'll work on that in a followup PR. I wanted to get this in for the 5.12 release if possible.
https://github.com/Ulauncher/Ulauncher/issues/764
Drops the "After" which has no effect when launched as a user service and point to graphical-session.target instead of graphical.target so that things work more consistently. 
Fedora 34, Gnome
=> Make systemd service file able to auto-start more consistently and include in the source tarball.

tests/api/server/test_ExtensionDownloader.py, tests/api/server/test_GithubExtension.py, ulauncher/api/server/ExtensionDownloader.py, ulauncher/api/server/GithubExtension.py
This fixed #769 in my basic tests.
Apart from the one line that actually extracts the files I just search for and replaced all occurrences of "zip" without fully understanding/checking the flow, but it worked in my tests and doesn't break the tests.
Can you verify it's working for you @tchar? I could install my fork of your extension reverted to when you had symlinks: https://github.com/friday/ulauncher-albert-calculate-anything, and the usd symlink was working. I didn't actually run your extension though.
=> Switch extension download link to use tar instead of zip (fixes symlinks)

ulauncher/config.py
closes #775 
In Wayland environments it's common to have `GDK_BACKEND=wayland,x11` which forces all applications linking to a version of GDK that supports wayland to use it and fallback to x11 in case of a older version (Older electron applications are a good example of applications that need the `,x11` in GDK_BACKEND).
This PR changes it so that Ulauncher does not abort with this configuration and proceeds with using Wayland as GDK backend.
=> Add support for GDK_BACKEND=wayland,x11

ulauncher/main.py
This adds a log when executing `ulauncher` with existing process already running that suggests user to use the `ulauncher-toggle` script instead of the full `ulauncher` which is about 250ms slower. This is especially useful for people using Wayland compositors who do their keybindings in compositor settings and can easily be mistaken to put `ulauncher` as the executable for menu keybind instead of the faster `ulauncher-toggle`.
=> Suggest `ulauncher-toggle` when `ulauncher` is already running

tests/api/server/test_ProcessErrorExtractor.py, ulauncher/api/server/ExtensionRunner.py, ulauncher/api/server/ProcessErrorExtractor.py
Extension logging was disabled when adding the extension error messages in Preferences. That stopped them from outputting to stderr (which is what's being used for logging, although I don't know why), disabling any logging from inside the extensions.
It should also be possible to change the logger to use stdout, but that code is in the extensions, and big part of why this is important imo is printing extension errors so devs can test them and see why it's not working.
=> Restore extension logging

tests/search/apps/test_AppDb.py, tests/search/test_SortedList.py, tests/utils/test_fuzzy_search.py, ulauncher/search/SortedList.py, ulauncher/search/apps/AppDb.py, ulauncher/utils/fuzzy_search.py
This changes the behavior of fuzzy matching
Levenstein distance is the amount of changes needed between one string of text to become the second one. The previous implementation didn't use it in that way, leading to low scores for what I would consider to be positive matches like "wif" for "Wi-Fi", because it was actually checking how many letters to change in "wif" to become "Wi-Fi gnome-control center" (which is most of them), and hence giving it a low score.
1. Instead of concatenating "Wi-Fi gnome-control center" or "Files nautilus" and running the query on that, it runs separately on "Wi-Fi" and "gnome-control center", and picks the one with the best score.
2. #558 Make a custom method for matching queries with results that counter-weights the "how many letters to change to become" …
=> Fuzzy improvements

scripts/help.sh, setup.py
none
This makes setup.py ignore the conftest.py which is now at the top-level. Otherwise, it installs it to `*/python*/site-packages/conftest.py` which is definitely not what we want. 
This breaks the Fedora build, and even if someone installed from the source tarball, there would be an extraneous file which shouldn't be there.
Feodra 34, Gnome 40
=> Don't install conftest.py

ulauncher/ui/windows/UlauncherWindow.py
#649 
It turns out that there was no need for any settings or fancy logic. Ctrl-n and Ctrl-p have no effect in current ulauncher and so are free for use. This PR simply support the Ctrl-n & Ctrl-p option specifically because Ulauncher is responsible for intercepting and responding to keypresses to scroll through results. For other emacs editing features, the user can enable the emacs keymap in Gtk as Ulauncher is a Gtk application. With custom themes it is even possible to enable it only for Ulauncher and not for other apps. However, all of that is out of scope for what Ulauncher is in charge of. Just like it doesn't implement "backspace" in the input field, neither does it implement all the normal emacs line editing commands. 
Fedora 34, Gnome 40
=> Implement standard shell/emacs ctrl-n/ctrl-p scrolling.

setup.py
#521
Installs the desktop and service file as part of setup.py.
Fedora 34, Gnome 40, X11
=> Install the desktop and service files as part of setup.py install.

scripts/build-deb.sh
The CI failure after merging my setup.py fixes which include the service file failed because the debian package script didn't copy over the service file. This adds that tweak.
I used the build scripts to build a debian package on a Ubuntu 16.04 VM (which appears to be the version used in the CI container) and installed it to test the fix. I also installed the generated package on Ubuntu 20.04. Note that to get the service file to work on the older Ubuntu additional configuration has to be done in order to provide ulauncher with the right environment, but works out of the box on the newer Ubuntu.
Ubuntu 16.04, Gnome 3.14
Ubuntu 20.04, Gnome 3.30
=> Add ulauncher.service file to the debian package.

ulauncher.service, ulauncher/api/shared/action/LaunchAppAction.py
This fixes ulauncher on wayland when started from systemd. It also makes sure GDK applications launched by ulauncher don't get forced into using Xwayland unnecessarily.
Fedora 34, Gnome 40
=> Wayland fix

data/ui/result_item.ui
Fixes #322 for the main ulauncher widget (not Preferences)
This PR switches from `GtkFixed` container to `GTKBox` so the layout won't break with large fonts. It also moves the width from the children to the parent so there's only one place to change if we need to override.
1x:
1.33x:
2x:
=> HiDPI support

ulauncher/api/shared/action/LaunchAppAction.py
Fixes #811.
I did replicate the issue described in #811. Interestingly there was only ever one defunct process, but it would stick around, sometime even chewing up 5% or so CPU until the next process was launched & terminated.  I'm not *super* happy with this solution, as I tend to try to reduce threads typically. However, I didn't come up with a great alternative. Some ideas I thought of:
- A single thread that would wait on any child (`waitpid(0,0)`) in a loop until there were none. Then some kind of singleton control to restart the thread again if needed with the next child. However, we don't want this to reap the extension children, so that doesn't work.
- Using the asyncio lib's subprocess support. Internally this uses an event loop implementation, and isn't something we are using …
=> Ensure child processes are reaped.

ulauncher/config.py, ulauncher/main.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/wayland.py, ulauncher/utils/xinit.py
I ran into #667 a few times recently as I was testing various things (normally it is hidden by auto systemd restarts :smile: ), so I decided to dig in a bit. Ultimate I took the direct approach, and just did what the error implies we should do. Call `XInitThreads()`.  It seems that multi-threaded access is fine, it just needs to have the right locks initialized.
I can't reproduce this bug consistently, but my changes have been running well for a while, so it doesn't seem to break anything that I can find. I'm posting this PR a bit early/premature so that other willing folks could test in their own setup to see if anything improves. Hopefully so!
Fixes #667 (hopefully)
- [-] Update the documentation according to your changes (when applicable)
- [-] Write unit tests for your changes (when …
=> Call XInitThreads() before any other GUI code initializes.

data/preferences/src/api/fixture.js, data/preferences/src/components/pages/Preferences.vue, ulauncher/search/apps/app_watcher.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/utils/Settings.py, ulauncher/utils/desktop/reader.py
This commit adds a configurable flag: `show-all-apps` to display all
apps despite the current desktop environement and the values:
- `OnlyShowIn`
- `NotShowIn`
from the `.desktop` files.
Closes #809
=> Add ability to show all apps

tests/api/server/test_GithubExtension.py, ulauncher/api/server/GithubExtension.py
Fixes #807 
This PR adds support for more versions of github urls when installing an extension
Previously, you could only add by using the following url format : https://github.com/Ulauncher/ulauncher-kill
Now, these variants are also supported
https://github.com/Ulauncher/ulauncher-kill/
https://github.com/Ulauncher/ulauncher-kill/tree/master
https://github.com/Ulauncher/ulauncher-kill/tree/master/
https://github.com/Ulauncher/ulauncher-kill.git
git@github.com:Ulauncher/ulauncher-kill.git
=> added support for more variants of github extension url

ulauncher/__init__.py
This loads the version from setup.cfg (only). It's comparable to the "VERSION" file used in my fork before, but without the file.
The script `tag-release.sh` (although it's kind of primitive still) bumps this version in setup.cfg if you create the release this way, so it should be the same as the tag.
The reason `git describe` was used before was to get the pre-release commit hash also if there were commits since the latest tag, however it seems like it created more problems than it solved In addition to not working with git worktrees, tags are not pulled by default, so there's a risk of git describe showing an invalid version.
=> V6 - Load the version from setup.cfg

Dockerfile, README.md, debian/control, docs/extensions/libs.rst, setup.cfg, ulauncher/api/shared/socket_path.py, ulauncher/config.py, ulauncher/search/QueryHistoryDb.py, ulauncher/search/apps/AppResultItem.py, ulauncher/search/file_browser/FileQueries.py, ulauncher/utils/setup_logging.py
Implements #843
It's changing the location of all the state files and the log to XDG_STATE_HOME. Note that XDG_STATE_HOME is very new, and it's likely that Ulauncher will be the first app to use it on users systems (it was for me), but this isn't a problem :). XDG_DATA_HOME is now only used to store extensions, and XDG_CACHE_HOME is only used to store css files generated for themes that extends other themes. I'm not sure if this is something we can work around, so we don't use XDG_CACHE_HOME at all.
Planning on doing more work with how the state files are stored, and making them less backward compatible, by switching to json. Otherwise I wouldn't have moved them.
=> Remove pyxdg dependency and switch to store state files in XDG_STATE_HOME

ulauncher/utils/fuzzy_search.py
This PR adds a fallback for Levenshtein if it's missing or outdated. I added it because I knew about the other method (it's how I originally implemented `get_matching_blocks()`), and it doesn't add a lot of code.
I don't think we strictly need this PR now, but we would need it for Xenial support (which we are pulling anyway with 6.0.0, and we stopped making Xenial releases for 5.14.1 also). I do think it's good to have in though, as the Levenshtein library has been in a sorry state for many years, and I'm not sure if it will continue to be packaged for distros.
Not sure this means we should:
* Make the tests run for both implementations?
* Remove the [CI server pypi package installation](https://github.com/Ulauncher/Ulauncher/pull/822/commits/6dfd4bc1e131a28a9b09fb6ab47409c388c543cf)
* …
=> Add fallback solution for searching if Levenshtein is missing or outdated

tests/utils/test_KeyValueJsonDb.py, ulauncher/utils/db/KeyValueJsonDb.py
KeyValueJsonDb is the class that handles state files and extension configuration files (but not the main config) in v6. This change makes it more robust, catching higher level errors and logging, so the app should never crash when it tries to save or load the file.
* The pathlib and json libraries will throw exceptions if the path exists but is not a file or if it's write protected (see #713, although that file is not covered by this class).
* If the file is corrupt or invalid JSON (this was a very common issue when we used Pickle: #111, #260, #290, #412, #443 #464, #469, #474, #699) it will throw too,
These exceptions will be caught and logged, but not treated as fatal. It will fall back to using an empty record and if it can't save it will just keep running anyway. It's not the end of …
=> Improve state file error handling

preferences-src/src/App.vue, preferences-src/src/api/fixture.js, preferences-src/src/api/jsonp.js, preferences-src/src/components/NavBar.vue, preferences-src/src/components/pages/EditShortcut.vue, preferences-src/src/components/pages/ExtensionConfig.vue, preferences-src/src/components/pages/Extensions.vue, preferences-src/src/components/pages/Help.vue, preferences-src/src/components/pages/Preferences.vue, preferences-src/src/components/pages/Shortcuts.vue, preferences-src/src/components/widgets/ExtensionErrorExplanation.vue, preferences-src/src/components/widgets/ExtensionRuntimeError.vue, tests/ui/windows/test_PreferencesUlauncherDialog.py, tests/utils/test_Router.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/utils/Router.py, ulauncher/utils/Settings.py
This gets rid of the worst code duplication described in #315, but does not fully solve the problem.
You still need to add each setting in four places:
* Settings.py (this is good)
* Preferences.vue display code (this is also good)
* Preferences.vue array to generate the computed properties  (this should not be needed, but at least you just have to add the name of the setting to the array)
* Fixture.js (this should not be needed imo - it should be able to load the defaults from Settings.py)
The big difference is that you no longer need to add the full computed properties (~15 lines of code each), and you don't need to add individual routes in PreferencesUlauncherDialog.py, not add the preferences to the /get/all-route if they are defined in Settings.py
=> Simplify preferences logic

.vscode/settings.json, docs/extensions/tutorial.rst, tests/api/server/test_ExtensionManifest.py, ulauncher/api/server/ExtensionManifest.py, ulauncher/api/server/ExtensionPreferences.py, ulauncher/api/server/ExtensionSearchMode.py
I was just experimenting with this and manage to implement the feature in 1h or so, that´s why I didn´t open an issue before.
This PR allows specifying an icon, associated with a keyword, that will override the global the extension icon defined in the extension manifest when the extension is triggered using that keyword.
The main use case for this feature, is for extensions that implement multiple keywords, with different goals, where the developer might want to use a distinctive icon for each.
For example, on my [docsearch](https://github.com/brpaz/ulauncher-docsearch) extension, which allows users to search on documentation sites that implement [Algolia Docsearch](https://docsearch.algolia.com/), the user can access, for example, the  Vue documentation, using  `docsearch vue <query>` …
=> Allow overriding extension icon at the keyword level.

tests/modes/calc/test_CalcMode.py, ulauncher/modes/calc/CalcMode.py
This fixes #874 and more critical floating point errors such as `1.1 + 2.2` evaluating to `3.3000000000000003`
=> Fix #874 and floating point errors in general for CalcMode

tests/modes/calc/test_CalcMode.py, ulauncher/modes/calc/CalcMode.py
Adding comma as a synonym for dot, for math expressions. This fixes #575, but means we can't accept comma or dot as thousand separators in the input (probably reasonable for our use anyway).
=> Treat both comma and dot as decimal separators for calc mode

docs/extensions/tutorial.rst, docs/source/ulauncher.utils.rst, tests/api/server/test_ExtensionManifest.py, tests/modes/apps/test_AppResultItem.py, tests/modes/file_browser/test_FileBrowserResultItem.py, tests/modes/shortcuts/test_ShortcutResultItem.py, tests/ui/windows/test_UlauncherWindow.py, ulauncher/api/server/ExtensionManifest.py, ulauncher/api/shared/item/ExtensionResultItem.py, ulauncher/modes/apps/AppResultItem.py, ulauncher/modes/calc/CalcResultItem.py, ulauncher/modes/file_browser/FileBrowserResultItem.py, ulauncher/modes/file_browser/alt_menu/CopyPathToClipboardItem.py, ulauncher/modes/file_browser/alt_menu/OpenFolderItem.py, ulauncher/modes/shortcuts/ShortcutResultItem.py, ulauncher/ui/ResultItemWidget.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/icon.py
There's a crazy amount of different icon loader methods that does almost the same thing: `load_image()`, `get_themed_icon_by_name()`, `get_app_icon_pixbuf()` and to some extent `get_file_icon()`.
* This PR merges them into one simple method that takes either a path or a themed icon name and returns a pixbuf (this means it implements #803).
* `get_file_icon()` is moved into the `FileBrowserResultItem` class (the only place that uses it).
* And the code to load the icon was moved to ResultItemWidget instead of duplicating it for all the ResultItem implementations.
=> Merge icon loading methods

tests/modes/file_browser/test_FileBrowserMode.py, ulauncher/modes/file_browser/FileBrowserMode.py
`~` (tilde) is a "dead key".
If a user types `~u` it becomes `ũ`, but it can also become two characters if the key pressed after `~` isn't a character that doesn't come with this diacritic variation. The user has to type the next character after `~` in order for us to even see that they pressed tilde.
This stands in conflict with our code for the file browser mode where we autocomplete `~` into `~/`, except if the user starts typing we will only see the query changing from an empty string into to `~/`. That is unless the user does something strange like pasting `~` from elsewhere, or escaping it by typing space after tilde.
For something intended to simplify for users it shouldn't be so hard to trigger. It's better not to have this autocompletion at all, especially as it is also …
=> Remove tilde autocompletion in file browser mode

docs/diagram-source.txt, docs/extensions/tutorial.rst, tests/modes/calc/test_CalcMode.py, tests/modes/file_browser/test_FileBrowserMode.py, tests/modes/file_browser/test_FileBrowserResultItem.py, tests/modes/shortcuts/test_ShortcutMode.py, tests/modes/test_Search.py, ulauncher/api/client/Extension.py, ulauncher/modes/BaseMode.py, ulauncher/modes/Search.py, ulauncher/modes/apps/AppMode.py, ulauncher/modes/calc/CalcMode.py, ulauncher/modes/file_browser/FileBrowserMode.py, ulauncher/modes/file_browser/FileBrowserResultItem.py, ulauncher/modes/shortcuts/ShortcutMode.py, ulauncher/ui/ItemNavigation.py
Instead of this
```py
from ulauncher.api.shared.action.RenderResultListAction import RenderResultListAction
```
...and returning `RenderResultListAction(list_of_items)`, you can now just return `list_of_items`.
This applies to all places RenderResultListAction was previously used, including the modes `handle_query` method, the extension query listener and and the extensions `on_enter` and `on_alt_enter` method.
For the extension methods this change is backward compatible, but as step two to this (in a future major release) we should remove `RenderResultListAction` completely as an action and only support returning lists. Primarily because this API imports a lot of internals and it's problematic to expose it as part of the API #920 #285, and it's also better to restrict the extension query …
=> Support list as a shortcut/alias to RenderResultListAction

ulauncher/modes/calc/CalcResult.py
Closes #688 , adds a comma sep for the calc mode result using the locale of the system. Does not add the comma on copy, the copy still gets the raw integer
=> Formatting the result with locale for calc mode

docs/diagram-source.txt, docs/extensions/tutorial.rst, ulauncher/api/extension.py
Adds new blank methods on the `Extension` class so users can extend and override those to bind the events without a ton of boilerplate code.
See https://github.com/friday/ulauncher-encoder/commit/cc382bea970e171b02fa3b3fef41cd9e72180ef1 (this extension/commit works only with the PR applied)
I have some further changes in mind for these like renaming the "preferences" event to "load" event, but wanted this to get merged first.
=> Automatic event binding

data/ui/UlauncherWindow.ui, tests/ui/test_ResultWidget.py, ulauncher/modes/ModeHandler.py, ulauncher/modes/file_browser/FileBrowserMode.py, ulauncher/ui/ResultWidget.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/display.py
This implements #246 and also should improve #561 a bit.
The window height is dynamic but with a max based on the window height now. Previously there was a fixed max height.
To prevent the window from being placed inconsistently or move up and down when you type I had to move it up a bit more.
The maximum amount of items result view will now be either the amount of characters in the jump code setting (default: 36) or 25 if the jump codes have been disabled. This can be changed. I just went with something. This is also applied for extensions results, not just the search results and the file browser results like before. So extension devs no longer should have to deal with this.
The theme css hides the actual scrollbar, but you can scroll with the scroll wheel and you can press up and down …
=> Scrollable result list view

ulauncher/utils/display.py
This is a newer Gdk method, and will return None if the user has not configured a primary
monitor (or has only a single monitor).
- [N/A] Update the documentation according to your changes (when applicable)
=> Don't rely on Gdk.Display.get_primary_monitor().

tests/ui/test_ItemNavigation.py, ulauncher/modes/ModeHandler.py, ulauncher/ui/ItemNavigation.py, ulauncher/ui/windows/UlauncherWindow.py
I fixed a few small issues I ran into today:
- I was getting spurious results show up when I first started Ulauncher, specifically a few of the fallback searches, but I had no query. Though interestingly it didn't happen every time. It definitely happened every time when I just typed spaces, but of course that wasn't a meaningful query because we `lstrip()` anyway. I also made it so that you can't even type the leading spaces, so that the user experience matches what is actually used.
- Looks like the extra space below the query box when there are no results was just due to a minimum size for the scrolling container. I added to code to just hide the container when there are no results.
- I had an issue where launching apps wouldn't close ulauncher. I found what appeared to be an inverted …
=> Small v6 bugfixes

CONTRIBUTING.md, Dockerfile, bin/ulauncher-toggle, debian/control, docs/extensions/libs.rst, setup.cfg, ulauncher.desktop, ulauncher/main.py, ulauncher/ui/AppIndicator.py, ulauncher/ui/windows/UlauncherWindow.py
Alternative implementation of #987, using Gtk.Application for the main loop. This handles stuff we had to do manually before with dbus, so we can remove the `python-dbus` dependency.
I also removed `gi.require_version('GLib', '2.0')` because I recently learned it's [not needed](https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/importer.py#L64)
As a nice side effect, this seems to get rid of the race condition issue with ulaucher-toggle. Previously I ran into that a lot on Wayland, but now I removed the `sleep 0.03` bit completely and it works every time (still need wmctrl though).
I kept things in the same file mostly because I wanted to keep the changes minimal. This PR is just the first part and there' s so much more this opens up for:
* Move the `UlauncherApp` to it's own …
=> Switch to Gtk.Application and make `ulauncher` command "toggle" by default

bin/ulauncher-toggle
This sends a direct `org.gtk.Application.Activate` message to the window reducing latency of toggling from 810ms to 9ms on a test machine.
=> Update `ulauncher-toggle` to use gdbus

ulauncher/modes/apps/AppResult.py
Some .desktop files contain an entry such as:
Keywords=key1;key2;key3
Which associates each of the semicolon separated keys with the
application.  These can be helpful when searching for the application.
=> Include keywords when searching for application.

tests/modes/calc/test_CalcMode.py, ulauncher/modes/calc/CalcMode.py
These fixes are meant to help for #1009
1. Fix bad fallback in `eval_expr()`. When `eval_expr()` failed it tried again, but stripped the last character. This would help to show for example "6" as the result  when typing "6 *", until you type a second number. But the fallback was wasteful and applied too wide. I replaced it with a much more specific regex replace that strips the last operator (including `**` which is one operator, but not `++` which is two)
2. I also added parenthesis completion for unfinished queries while I was at it.
3. Added memoization to avoid running the same evaluation repeatedly (should work especially well with the normalization)
4. Round the result to at most 15 decimals (as in #1009, but applied consistently and doesn't zero-pad results)
=> V6 calc improvements

tests/modes/calc/test_CalcMode.py, ulauncher/modes/calc/CalcMode.py
All the actual functionality is exactly as implemented by @Henje in #1009, but this is rebased over #1014 which solved some of the issues with #1009. `is_enabled()` has also been completely rewritten to use ast (just checking the root node) instead of regex, which made it easier to prevent false positives.
Also added more tests.
It seems pretty solid to me after these changes.
=> Calculator: Add trigonometric methods and constants

preferences-src/src/components/pages/ExtensionConfig.vue, preferences-src/src/components/pages/Extensions.vue, preferences-src/src/components/widgets/ExtensionErrorExplanation.vue, preferences-src/src/components/widgets/ExtensionRuntimeError.vue, tests/modes/apps/extensions/test_ExtensionDownloader.py, tests/modes/apps/extensions/test_ExtensionRemote.py, ulauncher/modes/extensions/ExtensionDownloader.py, ulauncher/modes/extensions/ExtensionRemote.py
Major rewrite to the extension remote class (previously very hard coded for GitHub)
It now written to be Gitea-compatible. GitHub is mostly Gitea-compatible as Gitea borrowed their APIs endpoints to begin with I believe.
It should now work with self hosted Gitea instances or Codeberg which uses Gitea (see #925).
Can be tested with: https://codeberg.org/Petrarca/ulauncher-ssh
Also managed to avoid hard coding the default branch or making a request with the "contents" API that both Gitea and GitHub supports rather than using the "raw" links. The result is a json object that has the file base64 encoded.
My original intent was just to clean things up to prepare for a PR like this, using a generic ExtensionRemore class and subclasses for each vendor. But these are so similar that that approach …
=> Add support for extensions hosted with Gitea and Codeberg

preferences-src/src/components/pages/Extensions.vue, preferences-src/src/components/widgets/ExtensionErrorExplanation.vue, ulauncher/api/shared/errors.py, ulauncher/modes/extensions/ExtensionRemote.py, ulauncher/ui/windows/PreferencesWindow.py
Fixes #679 (see: https://github.com/Ulauncher/Ulauncher/issues/679#issuecomment-913100543)
Shows a more friendly error for network issues / invalid links.
As a fallback solution the user is shown a link that opens the extensions directory in their default file manager. Extensions installed manually to this folder can't get updated by ulauncher and their folders won't be named "safely" as unique "extension ids", so our deduplication code won't work either. But they load/run.
=> Handle extension download network issues

bin/ulauncher-toggle, ulauncher/main.py, ulauncher/ui/windows/UlauncherWindow.py
This PR makes possible to pre set the query when calling `ulauncher-toggle` 
usage: 
`ulauncher-toggle` => Same  default behavior
`ulauncher-toggle -q some_query`
`ulauncher-toggle -q "some long query"`
`ulauncher-toggle --query=some_query`
`ulauncher-toggle --query="some long query"`
=> Add ulauncher-toggle query param to set up initial query.

tests/ui/windows/test_UlauncherWindow.py, ulauncher/modes/extensions/ExtensionDownloader.py, ulauncher/ui/windows/UlauncherWindow.py
This was originally added as a fix for #177, because (as explained there) extensions were placed in `~/.cache/ulauncher_cache/extensions/`, and system cleaner apps like BleachBit clears `~/.cache/`.
Since then, extensions are no longer stored in `~/.cache/`, but in `XDG_DATA_HOME` (usually `~/.local/share/ulauncher`), so it shouldn't be needed for this purpose any more. I would argue was the real fix for that issue.
It could be argued that this is still a good thing to keep this functionality for when people are backing up their dotfiles, migrating to a new system and didn't back up the extension dir. But I think that by trying to solve this problem, we are creating worse problems. We shouldn't make changes to the extension directory unless users ask to. For example, you could be deleting …
=> Remove "download_missing" extension functionality

docs/extensions/events.rst, ulauncher/api/extension.py, ulauncher/modes/extensions/ExtensionController.py, ulauncher/modes/extensions/ExtensionRunner.py
In v5, the way extension developers handle preferences being loaded initially was to subscribe to the `PreferencesEvent`. This PR adds a much better way (so we can remove this event in the future).
It's now done in the `Extension.__init__` method. This makes things less confusing for users, without multiple extension init events/methods, and this way the extension will be able to access the preferences as soon as it's created, without delays/waiting.
```py
class MyExtension(Extension):
def __init__(self):
super().__init__()
value = self.preferences.get('my_preference_id')
```
It is sending the whole preferences object as stringified json in an environment variable, then loads it again. It might be inefficient, but the object is small and should be fast to format and parse.
=> Load extension preferences directly in  __init__

.pylintrc, tests/ui/windows/test_PreferencesWindow.py, tests/ui/windows/test_UlauncherWindow.py, ulauncher/main.py, ulauncher/ui/AppIndicator.py, ulauncher/ui/UlauncherApp.py, ulauncher/ui/windows/PreferencesWindow.py, ulauncher/ui/windows/UlauncherWindow.py
In v5 UlauncherWindow is the root instance and works as a global data storage. In v6 we've changed that so we also have an application instance.
This PR primarily moves the stuff from UlauncherWindow that doesn't concern the window out to the UlauncherApp or main.py. UlauncherApp handles the initialization of the UlauncherWindow, PreferencesWindow, AppIndicator, ExtensionServer/Runnner and the callbacks/communication between these windows is handled via the Application also, so there's no circular imports where UlauncherWindow imports PreferencesWindow that imports UlauncherWindow.
I also completely rewrote the AppIndicator class since it was overly complicated for what it did.
This will allow further improvements to the logic and reduce resource usage.
=> Refactor base classes

tests/modes/apps/extensions/test_DeferredResultRenderer.py, ulauncher/api/shared/event.py, ulauncher/modes/extensions/ExtensionController.py
This is a different solution instead of #287 (which was merged into the v6 branch but never released and now reverted) 
This solution is better and will fix the issue without requiring extension devs to change their code. Extensions will receive a normalized user query where `get_keyword()` returns the default they specified, regardless of what users changed the keyword to.
It also removes the need to pass preferences to the event, and this will me simplify the API a bit more in another place.
=> Rework extension keyword

docs/extensions/tutorial.rst, ulauncher/api/extension.py, ulauncher/api/shared/event.py
Before this, we always passed the event, but the event is (at best) just a wrapper to get the arguments. This passes the argument directly.
This is only changes things we introduced in v6 and hence it's backwards compatible with v5.
=> Pass custom arguments directly to extension's event listener methods

ulauncher/ui/AppIndicator.py
Implements https://github.com/Ulauncher/Ulauncher/issues/1068
It's not possible to distinguish left or right click with libindicator, so the next best option is to add a menu item and also set it as secondary target, which means that it is called when a middle click is received
=> add "Show Ulauncher" menu item to tray menu and set it as secondary target

docs/extensions/tutorial.rst, preferences-src/src/api/fixture.js, tests/modes/apps/extensions/test_ExtensionManifest.py, tests/modes/apps/extensions/test_ExtensionRemote.py, ulauncher/modes/extensions/ExtensionManifest.py, ulauncher/ui/preferences_context_server.py
The "description" field in the manifest is never actually used anywhere. It's not shown in the preferences view, and the description that is shown in the app for the keyword is the keyword description (as it should be).
GitHub repos have their own descriptions and also the readme. The extension database for https://ext.ulauncher.io/ uses it's own description input field when you submit descriptions.
If we at a later point need the description again I guess his would be a move in the wrong direction, but I see no reason to have it. We have "instructions" now for actually important messages about compatibility that will be shown in the preferences UI. In addition we could use the readme markdown (would require some dependency to format it. It is much longer, but also much more likely to …
=> Remove unused property "description" from manifest

docs/extensions/tutorial.rst, preferences-src/src/components/pages/ExtensionConfig.vue, tests/modes/apps/extensions/test_ExtensionController.py, tests/modes/apps/extensions/test_ExtensionManifest.py, ulauncher/modes/extensions/ExtensionController.py, ulauncher/modes/extensions/ExtensionManifest.py, ulauncher/modes/extensions/ExtensionMode.py, ulauncher/modes/extensions/ExtensionRunner.py, ulauncher/modes/extensions/ExtensionServer.py, ulauncher/ui/preferences_context_server.py
This changes manifest.preferences to a dictionary, which makes more sense:
1. Dictionary keys have the same constraints as what we need for the id (unique, non-empty strings), removing the need for some tests, validation and documentation.
2. Easier to declare/read (less code).
3. We can find the preference with `preferences.get(id)` instead of looping through all of them (slower and more code needed).
This change is fully backwards compatible. `ExtensionManifest` reformats the manifest as it loads it (this is something that I plan to let extension developers use to migrate extensions).
=> Change manifest.preferences to a dictionary

docs/extensions/tutorial.rst, tests/modes/apps/extensions/test_ExtensionManifest.py, tests/modes/apps/extensions/test_ExtensionRemote.py, ulauncher/modes/extensions/ExtensionManifest.py, ulauncher/modes/extensions/ExtensionRemote.py
I don't know why this was originally changed from `api_version` to `required_api_version`. The V1 format was actually compatible for the V2 parser to read. It wasn't really adding anything. If anything, the wording which would be correct would be `supported_api_versions` (plural). But there's no need to be so specific/verbose imo.
This PR changes it back **for the manifest**. For versions.json it's still `required_api_version`, but versions.json will eventually be dropped for a [better solution](https://github.com/Ulauncher/Ulauncher/commit/ac138ef3eda498b7b0ecd2aa652984f5e0dc49c1).
This change is fully backwards compatible. `ExtensionManifest` reformats the manifest as it loads it (this is something that I plan to let extension developers use to migrate extensions).
=> Rename "required_api_version" back to "api_version"

preferences-src/src/components/widgets/ExtensionErrorExplanation.vue, tests/modes/apps/extensions/test_ExtensionRemote.py, ulauncher/api/shared/errors.py, ulauncher/modes/extensions/ExtensionRemote.py
Already removed it from the documentation before.
We have a much better solution in place: ac138ef3eda498b7b0ecd2aa652984f5e0dc49c1. You can make a git tag named `apiv3` or `apiv3.1` etc. This is easier for everyone. You don't need to make updates in mulitiple repos and unlike versions.json it can't fail (it's impossible to make a tag that points to an invalid reference) and you don't need a whole page of documention 256a495428e50e2c39184360788c88509d148362. I haven't actually added how to use the tags yet, because that won't come in effect until updating to API v4. For updating to v3 all you need is to bump the api version in the manifest.json in your main branch. If you don't want your main branch to be for the current version, then you can tag the current version instead.
Going to …
=> Completely remove versions.json support

ulauncher/config.py, ulauncher/utils/migrate.py
Implements #845, but without deleting any files you would want to keep if you run into issues with v6 and want to revert.
If you want to delete those you have to drop into a python relp and run
```py
from ulauncher.utils.migrate import v5_to_v6_destructive
from ulauncher.config import PATHS
v5_to_v6_destructive(PATHS)
```
This script doesn't touch the settings.json file. It's handled by the Settings class to convert dash to underscore in the key names. If you run v6 and never change the settings in the first (main) page they will still work for v5, but if you do change them you have to set them up again (only takes seconds) or replace the underscores with dash. Ex: `sed -i 's/_/-/g' ~/.config/ulauncher/settings.json`. Note that this example replaces ALL underscores by dash, including the …
=> Migrate v5 data files to v6

ulauncher/utils/launch_detached.py
This PR fixes issue #1110 which is caused by the presence of os.setsid. I assume this could be useful on systems missing systemd-run so this PR keeps that functionality intact in that case while disabling it when systemd-run is present (where os.setsid shouldn't have an impact). I did test this and apps started by ulauncher don't stop when ulauncher is stopped.
=> Fix clion crash (#1110)

tests/ui/windows/test_HotkeyDialog.py, tests/ui/windows/test_UlauncherWindow.py, ulauncher/__init__.py, ulauncher/api/shared/action/CopyToClipboardAction.py, ulauncher/main.py, ulauncher/modes/file_browser/FileBrowserMode.py, ulauncher/ui/AppIndicator.py, ulauncher/ui/ResultWidget.py, ulauncher/ui/UlauncherApp.py, ulauncher/ui/preferences_server.py, ulauncher/ui/windows/HotkeyDialog.py, ulauncher/ui/windows/PreferencesWindow.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/icon.py, ulauncher/utils/wm.py
I always found these `gi.require_version(s)` statements to be super messy and non-standard, adding a lot of verbosity so I moved them all to `__init__.py`
It's faster to set `gi._version = {}` directly instead of using `gi.require_versions({})`, but it's not an official API. So I didn't do it. But after this is effectively all that `gi.require_version(s)` does besides validation: https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/__init__.py#L132
=> Move gi version declaration to __init__.py to avoid having to declare repeatedly

data/styles/preferences.css, data/themes/adwaita/theme.css, data/themes/dark/theme.css, data/themes/light/theme.css, data/themes/ubuntu/theme.css, preferences-src/src/components/pages/Preferences.vue, ulauncher/main.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/Settings.py
In 474ea7625ac4dad4cc68bdf0e35647526d6efde3 I managed to get the black border issue and solved it for myself by setting the "visuals" to rgba. I also noticed that if rgba is not supported (when not using a compositor) we can detect this and fallback. That solution looked like this:
https://github.com/Ulauncher/Ulauncher/blob/474ea7625ac4dad4cc68bdf0e35647526d6efde3/ulauncher/ui/windows/UlauncherWindow.py#L42-L50
https://github.com/Ulauncher/Ulauncher/blob/474ea7625ac4dad4cc68bdf0e35647526d6efde3/ulauncher/ui/windows/UlauncherWindow.py#L107-L108
I'm not sure this will work for everyone and in all scenarios, but I want to remove it while we're making a major release so we can get rid of this setting in case it does work and bring it back otherwise. [The …
=> Remove the no-shadow setting

ulauncher/utils/wm.py
by only loading/calling wnck when running under X11.
Fixes: #1168
=> fix: failure to launch with GDK_BACKEND=wayland

CONTRIBUTING.md, ulauncher/api/result.py, ulauncher/modes/calc/CalcResult.py, ulauncher/modes/extensions/ExtensionController.py, ulauncher/ui/AppIndicator.py, ulauncher/ui/ResultWidget.py, ulauncher/ui/UlauncherApp.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/WebKit2.py, ulauncher/utils/decorator/singleton.py, ulauncher/utils/desktop/notification.py, ulauncher/utils/icon.py, ulauncher/utils/wm.py
Gobject/Gtk now works even worse with Mypy (0.990+) than it does with Pylint.
Gobject is a FFI integration and an anomaly, and modern more strictly typed Python doesn't like what it can't understand.
Also fixes PEP 484 / implicit optionals error that was added (correctly so) in 0.990, and removes/updates outdated type annotations comments.
=> fix: mypy 0.990+

ulauncher/ui/windows/UlauncherWindow.py
The event coordinates are relative to the widget being clicked on instead
of the window. Therefore it was possible to activate dragging by clicking
on the results.
Add an EventBox widget around the draggable area and subscribe to the
click event only on that instead of the whole window in order to fix it.
Taken from #1172 + fixed the coordinate relative to be relative to the window.
=> fix: Fix dragging when clicking on results

ulauncher/ui/LayerShell.py, ulauncher/ui/windows/UlauncherWindow.py
Uses https://github.com/wmww/gtk-layer-shell to set up the Ulauncher window as a layer window, which drops decorations, allows positioning and displaying over fullscreen windows.
Fails gracefully if the module cannot be loaded.
The extension is currently supported by wlroots based desktops (e.g Sway) and KDE.
Moving the window to a different position is not supported in this mode yet, but possibly could be implemented by changing the margin and or anchor edges.
Requires Ulauncher to be using wayland i.e. explicitly setting `GDK_BACKEND=wayland`.
Q: Should I add some notes about this "experimental" option and how to change e.g. the systemd user service file?
Fixes: https://github.com/Ulauncher/Ulauncher/issues/701
=> feat: Try to use wlr-layer-shell protocol on wayland

.github/workflows/checks.yml
Small improvements to checks workflow.
* Don't want to run it for v5 branch (not sure if it will run on PRs for v5 though, but I usually push directly to v5 if there's anything)
* Switched from cache-apt-pkgs-action to just `apt`. apt packages are pre-built so it's already like having a free cache, and overall it seems faster, and `cache-apt-pkgs-action` also didn't work with https://github.com/nektos/act (although act fails at a later point anyway)
=> ci: checks improvements

ulauncher/ui/windows/UlauncherWindow.py
As per discussion in https://github.com/Ulauncher/Ulauncher/pull/1172#issuecomment-1371922928
I don't remember why I couldn't use this before. It may have been related to other changes we have made since.
=> feat: use begin_move_drag for moving window

ulauncher/ui/AppIndicator.py, ulauncher/ui/UlauncherApp.py
Inspired by the mixin from #1172. I think this is cleaner with both having `self` as the app
=> refactor: make appindicator a class mixin

.github/workflows/lint.yml, tests/api/shared/action/test_RenderResultListAction.py, tests/modes/apps/extensions/test_DeferredResultRenderer.py, tests/ui/test_preferences_server.py, ulauncher/api/shared/action/RenderResultListAction.py, ulauncher/api/shared/action/SetUserQueryAction.py, ulauncher/modes/extensions/DeferredResultRenderer.py, ulauncher/ui/preferences_server.py, ulauncher/ui/windows/PreferencesWindow.py
This can and should be improved further, but this was a small easy win in the meanwhile.
Also added better error handling, showing an error or warning if calling actions from within the extension runtime or otherwise outside of Ulauncher.
=> refactor:  Use gio.application.get_default() to avoid cyclic imports and unnecessary complexity

bin/ulauncher
I have done some tests and XWayland by default without workarounds is arguably more broken, or at least broken in more critical ways than pure Wayland. It will ultimately depend on your setup. For example XWayland works good if you don't use multiple displays, disable focus stealing prevention and disable display scaling (use text scaling instead). But if you do use multiple displays there's no workaround.
The only really bad issue for Xwayland is lack of positioning, but the window manager can sometimes handle that ok enough either by defaulting to center, center all windows (ex on gnome: `gsettings set org.gnome.mutter center-new-windows true`) or center Ulauncher specifically.
Movable window and "Always on top" is not nearly as important imo.
It may be possible to fix the focus …
=> feat: default to pure wayland on wayland

preferences-src/src/components/pages/ExtensionConfig.vue, tests/modes/apps/extensions/test_ExtensionDownloader.py, tests/modes/apps/extensions/test_ExtensionRemote.py, ulauncher/modes/extensions/ExtensionDb.py, ulauncher/modes/extensions/ExtensionDownloader.py, ulauncher/modes/extensions/ExtensionRemote.py
The GitHub API have too strict rate limits.
The discover references is what the git client uses internally to fetch from the server, so it's like using git but without the extra dependency. It also has the benefit of working the same for all git servers.
Unfortunately you can't get timestamps for the commits this way. Just the references and hashes. To get timestamps you need to clone the actual repo locally. It's possible to use the old way to fetch only the date when we know there is an update available and hence it would avoid the rate limits, but I think it doesn't justify adding all that old complexity back.
Effectively the difference is:
1. This solution requires less code, and less requests, and should be easier to support for more git hosts (assuming we can still get a tar …
=> fix: Rewrite ExtensionDownloader to use git repo discover references

.pylintrc, docs/extensions/debugging.rst, docs/extensions/tutorial.rst, preferences-src/src/components/pages/ExtensionConfig.vue, preferences-src/src/components/pages/Extensions.vue, preferences-src/src/components/widgets/ExtensionErrorExplanation.vue, tests/modes/apps/extensions/test_ExtensionRemote.py, ulauncher/modes/extensions/ExtensionDownloader.py, ulauncher/modes/extensions/ExtensionRemote.py
While #1196 solved the issue with hitting GitHubs API rate limits, and also made the code simpler and more standardized, it still assumed that:
1. All repos are in the form of `https://host.tld/user/repo`
2. All repos have a tarball download endpoint
This was true for all the hosts we supported, and with this PR if the host is github, gitlab or codeberg or if the user doesn't have git installed it, it keeps using the old (tarball) install, as that's faster.
But if the user has git installed and trying to install from any other host it will instead use `git clone --bare` and `checkout`, which should work for any git host. This includes local paths such as `file:///home/me/my-code/my-ulauncher-extensions` (the `file://` prefix is optional, so you can use just `/path/to/dir`. It will store …
=> feat(ext_remote): use git if installed to support any repo

ulauncher/utils/environment.py
When running Ulauncher on ArcoLinux I get a KeyError as such:
```py
╰─ ulauncher                                                                                  
Traceback (most recent call last):
File "/usr/bin/ulauncher", line 22, in <module>
from ulauncher.main import main
File "/usr/lib/python3.10/site-packages/ulauncher/main.py", line 8, in <module>
import ulauncher.utils.xinit  # noqa: F401
File "/usr/lib/python3.10/site-packages/ulauncher/utils/xinit.py", line 4, in <module>
from ulauncher.utils.environment import IS_X11_COMPATIBLE
File "/usr/lib/python3.10/site-packages/ulauncher/utils/environment.py", line 20, in <module>
DISTRO = os_release["PRETTY_NAME"] or "Unknown Distro"
KeyError: 'PRETTY_NAME'
```
because my `/etc/os-release` file does not have a `PRETTY_NAME`
```asciidoc …
```
=> Use get instead direct key index for DISTRO environment

tests/modes/apps/extensions/test_DeferredResultRenderer.py, ulauncher/api/result.py, ulauncher/modes/apps/AppResult.py, ulauncher/modes/calc/CalcResult.py, ulauncher/modes/file_browser/CopyPathToClipboardResult.py, ulauncher/modes/file_browser/FileBrowserResult.py, ulauncher/modes/file_browser/OpenFolderResult.py, ulauncher/modes/shortcuts/ShortcutResult.py, ulauncher/utils/basedataclass.py
Makes the Result instances JSON serializable.
It's also possible to set any property this way, which is something I plan to utilize in further extension API rework. However the current implementation allows overriding the methods I think. Not sure how to handle that
This is a breaking change since the current `Result` (before the PR) allows passing positional arguments. The extension documentation never mentioned that, and I haven't found a single extension written like that when checking the [github code search](https://github.com/search?q=ExtensionResultItem%28+language%3APython&type=code&l=Python). So I think it's fine as long as it's documented as a breaking change.
This is the first a step towards getting rid of pickle for extension communication. Everything we send as of this PR is …
=> refactor!: make results json serializable

tests/api/client/test_Client.py, tests/modes/apps/extensions/test_ExtensionServer.py, ulauncher/api/client/Client.py, ulauncher/modes/extensions/ExtensionServer.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/framer.py
I've been pushing underlying PRs and commits to enable this change recently: #1221, #1230, 6706467, ee73262 #1237 d8f65e2 a23ff49
It's working well for me, although pickle is apparently more compact, so the result is the messages are actually much longer now (sometimes more than twice as big).
I tested with ulauncher-clipboard and sending 200 items (not that my window is big enough to render them all). The result size is 54196 bytes instead of 22773 before this PR.
But that still wasn't noticably slow. JSON is much faster to serialize and parse (more than 10x) and it is generally better and a step towards supporting extensions in other languages #283
I'm not sure how much the PickleFramer class (now renamed) still makes sense though. It looks to me like it's more about the socket …
=> refactor: switch extension message format from pickle to json

ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/Settings.py
The purpose of this change is to assist the Vim community by enabling the use of ctrl-j/k for navigating through Ulauncher results. This combination is widely recognized as a navigation hotkey and is currently supported by most Linux, Mac, and Windows launchers.
The change has been tested successfully on Ubuntu 23.04.
=> feat(#204): added ctrl-j/k navigation hotkeys

bin/ulauncher
Fixes #1276
Tor avoid Arch users creating issues here or for the package after Python upgrades, this will try to recover from a Python upgrade and load the Ulauncher from the old module path, but add a warning and reference to #1280:
For other cases it will show this:
=> feat: handle python not being able to import the ulauncher module

bin/ulauncher-toggle
This pull request updates the ulauncher-toggle script to comply with POSIX sh.
Without this, ulauncher-toggle may not work, since `/bin/sh` only guarantees POSIX sh compatibility and may not support Bash-specific extensions.
For instance on Debian, where `/bin/sh` is linked to **d**ash, I get an error:
```
$ ulauncher-toggle 
/usr/bin/ulauncher-toggle: 6: Syntax error: Bad for loop variable
```
I used [shellcheck](https://www.shellcheck.net/) to validate that the script is now compliant.
=> Update ulauncher-toggle script to comply with POSIX sh

ulauncher/ui/ResultWidget.py, ulauncher/ui/windows/UlauncherWindow.py
Small fix to allow double and triple click to highlight input text in Cinnamon. Fixes https://github.com/Ulauncher/Ulauncher/issues/1297
Behavior before:
[cinnamon-2023-11-02T105036+0100.webm](https://github.com/Ulauncher/Ulauncher/assets/85798751/a9c9c7df-2816-49fd-91a3-e8a9646559f5)
Behavior after:
[cinnamon-2023-11-02T110210+0100.webm](https://github.com/Ulauncher/Ulauncher/assets/85798751/95f1c752-cad9-4ae9-83bc-b99ff3118645)
Can't test this myself but should probably test this in some different environments including using touchpad (maybe touchscreen) to see if they also work with the `Gdk.EventType.BUTTON_PRESS` event type
=> Fix window shifting on double and triple click in some environments

bin/ulauncher, conftest.py, docs/conf.py, docs/source/ulauncher.utils.rst, setup.cfg, setup.py, ulauncher/__init__.py, ulauncher/config.py, ulauncher/ui/ResultWidget.py, ulauncher/ui/preferences_server.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/get_icon_path.py, ulauncher/utils/load_icon_surface.py
Refactored the namespace package (`__init__.py`) so it doesn't need to be overwritten in the build.
This was one of the quirky things needing special code in setup.py.
=> refactor: static namespace module

ulauncher/modes/extensions/ExtensionRunner.py
This code has been in the extension implementation since the original design https://github.com/Ulauncher/Ulauncher/pull/116/files#diff-96890e4141fb84b7c4642a31a1f51c1ead12e61994fbc4a62e2a7d549913a233R59
I don't think we really need it. All the extension should need is the ulauncher application added to its path so it can import the ulauncher module even if it's not installed (running from source)
`PYTHONPATH` is still used as a way to send that path to the extensions though.
=> refactor: skip propagating PYTHONPATH from the app to extensions

.gitignore, CONTRIBUTING.md, default.nix, flake.lock, flake.nix, nix/default.nix, scripts/tests.sh, tests/modes/shortcuts/test_RunScript.py, ul
This PR provides a Nix build for v6+ based off [nixpkgs' `ulauncher` build](https://github.com/NixOS/nixpkgs/blob/e44462d6021bfe23dfb24b775cc7c390844f773d/pkgs/applications/misc/ulauncher/default.nix)
summing up it allows you to:
- use `v6` branch externally in your own Nix configurations (be it NixOS or just a Nix package manager),
- develop locally with Nix-built Python env (not sure how much is it real `virtualenv`),
- continously lint and test whenever rebuilding the code (during packaging step),
=> build and develop using Nix package manager

ulauncher/utils/launch_detached.py
I am not sure what exactly `$GDK_BACKEND` does, but I am setting this to `wayland` in my system config and the code comment indicates it should not clear value of `wayland` itself?
picked from #1307
=> do not clear GDK_BACKEND=wayland

nix/default.nix
`ruff check .` is not happy about the missing usage of `PATHS` after the patch
=> nix: fix `ruff` check on PATHS

preferences-src/src/components/pages/ExtensionConfig.vue, ulauncher/ui/preferences_server.py
Old look:
New look: 
Bonus feature: You can now see and edit the fields for stopped extensions (previously the limited UI prevented this). Obviously extensions won't get the preferences change event, but they should not rely of that.
"Report issue" button has been removed. It was always unsafe to assume that the repo had an open issue tracker at `{repu_url}/issues`. GitHub defaults to that (but it can be disabled). But we also support more than GitHub. So for the little convenience benefit of saving a click it's not worth it.
=> feat(ext ui): replace preferences dropdown with dedicated buttons

.github/workflows/tests.yml, nix/default.nix
Cherry-picked from https://github.com/Ulauncher/Ulauncher/pull/1330#pullrequestreview-1801933060 (credit to nazarewk). It wasn't working in that PR, but that was due to issues with the docker image which have been fixed since.
I'm keeping this as a separate PR for now since this runner is a bit slow (understandably) compared to the others and I'm not sure I want this to run for every push (because we have limited free ci minutes).
=> ci: add test to validate nix package can be built

.github/workflows/draft-release.yml, scripts/build-targz.sh, scripts/help.sh, ul
This is the second time I rewrite this. The first rewrite (c9066f5dcfe78e05bdca7d7723edd00725c09107) was because I though the original version was convoluted and added an unnecessary build dependency `rsync`, which feels hard to motivate just for this, and I wanted to reuse the standard python setuptools sdist `python3 -m build --sdist`.
This however came with a lot of caveats
* It renames the Ulauncher version to follow the [python version standard](https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers), for example renaming `1.2.3-beta1` to `1.2.3-b1`.
* It uses ulauncher.egg-info to select files if it exists, instead of setup.py, so you need to `rm -rf ulauncher.egg-info`  first if you make changes to setup.py …
=> chore: simplify sdist

.github/workflows/draft-release.yml, .github/workflows/tests.yml, nix/default.nix, scripts/tests.sh
I don't know why this patch was needed in the first place, but the cache provider isn't making these tests faster anyway, so might as well always disable it and not need the patch.
=> chore: always use pytest no:cacheprovider

ulauncher/utils/launch_detached.py
The switch to GLib.spawn_async reintroduced #754 because `child_setup=os.setsid` doesn't work. 
Reproduction: Stop the ulauncher systemd service and run `make run` or `ulauncher -v` in a terminal. Launch an app which isn't already running or part of the OS (for example Chrome, Firefox but not for example Nautilus). Switch back to the terminal and press ctrl+c to kill Ulauncher.
With this PR it should not kill any apps when Ulauncher is killed, but before it did.
I have tested and we specifically need both setsid and nohup  if Ulauncher is not running as a systemd service. Running systemd instead of this does not solve the problem because that process will still be killed.
`standard_output=True, standard_error=True` is needed to prevent nohup from creating `nohup.out` files
=> fix: restore setsid if not running ulauncher through systemd

ulauncher/utils/launch_detached.py
This replaces the call out to the nohup and setsid executables with an in code implementation of re-opening the standard file descriptors to /dev/null. This avoids creating the pipes that has no reader and thus could block after enough output from the child process.
=> fix: Don't setup unmonitored pipes to child processes.

preferences-src/src/components/pages/Preferences.vue, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/Settings.py
Fixes #804
Pasting cannot be supported cross desktop. There is no API for it. The best we can do it to trigger the desktop to think the user pressed the keyboard combination to paste. So the solution both depends on the users keyboard combination and being able to trigger it (xdotool only works for X11).
=> feat: add copy hook

preferences-src/src/components/pages/Preferences.vue, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/Settings.py
Fixes #1277
Feels pretty rudimentary. I would prefer to be able to drag visually to resize, and if not, to check the window size to make sure we never try to render it bigger than the window. But we're limited due to Gtk4 and Wayland.
I managed to kill my Gnome session while trying what would happen if I set it to 9999, so I decided to restrict it to max 2000px. I think anyone with a huge screen would use display scaling of 2x or more. And if not they can let us know.
The better way seems to be to let the window manager handle this and set it up so it will remember, but we're at least a couple of major steps away from being able to do that (need to enable CSD and store settings with GSettings?): https://developer.gnome.org/documentation/tutorials/save-state.html
=> feat: add setting for window width

ulauncher/modes/ModeHandler.py, ulauncher/ui/windows/UlauncherWindow.py
Previously the triggers were updated for every keystroke. Now instead we refresh them when we open the window and then not again until the next time we open the window
=> perf: avoid refreshing triggers for every keystroke

ulauncher/modes/ModeHandler.py, ulauncher/modes/extensions/ExtensionSocketServer.py, ulauncher/ui/UlauncherApp.py, ulauncher/ui/windows/UlauncherWindow.py
Closes #1151 
After refactoring elsewhere, making the Window class much more isolated (#1378) we can now easily do this.
Two advantages:
* Instead of reusing the previous window we re-draw the window when you open it now, each time. This way for example if you search for an app, close ulauncher, and uninstall it, it will not show up next time you re-open the launcher (this was always a bug imo, but no one complained about it).
* #1304 will now be possible and easy (although systemd integration might still cause problems for it)
* Should use less memory, but this seems insignificant when compared to #1063.
=> feat: close window instead of hiding

preferences-src/src/components/pages/Preferences.vue, ulauncher/modes/ModeHandler.py, ulauncher/utils/Settings.py
This reverts commit 9aca04c5f044ab1365c712086c20c338726faee6 (#1371)
I would like to bring this back and support this feature, but having tested it myself a bit with the example command it just doesn't work very well. I realized part of this is that xdotool is slow, but another part is that Gtk needs to sync/store the data that was copied in the background before it can be pasted, and there is no way to force this or any event to listen to.
It's the same problem that causes setting the clipboard and exiting the Gtk mainloop too soon after to lost the clipboard content: https://discourse.gnome.org/t/setting-clipboard-contents-from-a-script/15072, except we can get around that by waiting to exit the app after copying. 0.02s seems "enough", but I prefer to wait much longer to be on the safe …
=> Revert "feat: add copy hook"

preferences-src/src/components/pages/Preferences.vue, ulauncher/ui/UlauncherApp.py, ulauncher/utils/Settings.py
Fixes #1304 (have verified that it doesn't trigger the focus-stealing prevention)
Changes the Ulauncher behavior so that just running Ulauncher without first starting it as a daemon will run Ulauncher and close the app as soon as the window is closed. This means no resource usage when idle, but instead it will start slower (just short of a second on my system, but deferring extension startup made it launch much faster ~0.6s, and other minor performance improvements might help too, such as conditioning the `v5_to_v6` compat/migration script so it only runs the first launch after upgrading). This might not sound much, but it's huge difference to the near-instant experience when you run we're used to.
Using Ulauncher this way is not currently recommended unless you know the trade-offs, …
=> feat: add experimental option to use ulauncher daemonless

ulauncher/internals/result.py, ulauncher/modes/file_browser/file_browser_mode.py, ulauncher/ui/ulauncher_app.py, ulauncher/ui/windows/ulauncher_window.py, ulauncher/utils/wm.py
Defers loading the slow modules for EWMH, fuzzy_search, ItemNavigation, ResultWidget, AppResult and PreferencesWindow until we need them.  Additionally deferred hotkey_controller and tray_icon although they were not that slow.
Remaining culprits:
* load_icon_surface is oddly slow ~35-40ms
* JsonConf takes a few ms (around ~7ms). Maybe most of that is due to BaseDataClass
* I didn't test, but I know that loading the Gtk app with dbus etc is time we could shave off by just showing the window.
* Python itself (maybe using cython could help, but then [there is a risk to introduce memory bugs](https://pythonspeed.com/articles/cython-limitations/)?)
=> perf: lazy load slow modules that we don't need for showing the window

scripts/build-rpm.sh
In Ulauncher v5 the rpm build process currently returns an error.
`error: can't copy 'ulauncher.service': doesn't exist or not a regular file`
This was already mentioned in issue #1156 for Fedora 36.
Since I encountered the same issue when running `./ul build-rpm 5.15.7 alma9.4`, I investigated.
This is due to the build script at `scripts/build-rpm.sh` missing the line for ulauncher.service in its rsync command.
I only tested this for Almalinux 9.4 but it should make no difference when it comes to Fedora.
=> Update build-rpm.sh to include ulauncher.service

ulauncher/ui/windows/ulauncher_window.py
Most of the old APIs we use here are deprecated since Gtk 3.20, and if I enable deprecation warnings (which I think is a good idea for dev mode) I get  a lot of these:
The GTK docs recommend using [`Seat.grab()`](https://docs.gtk.org/gdk3/method.Seat.grab.html) instead, which skips one step. However `Seat.grab()` takes different params compared to [`Device.grab()`](https://docs.gtk.org/gdk3/method.Device.grab.html). The first and third params (window and True) are exactly the same, but not the rest.
So I would appreciate help to confirm this works since I don't use or know how to use "Sloppy focus mode".
=> refactor: rewrite device pointer grabbing to avoid using deprecated apis

makefile
If you have these packages installed on your system pip tries to use those versions.
This has the potential to break our scripts since a global mypy for example won't
work with the pgobject stubs installed for the .venv
This does make it a few seconds slower to re-run "make python-venv" on my system (6-7 seconds in total instead of 3-4 seconds, so no big deal imo).
=> chore: ignore system packages that satisfy the required dev dependencies

makefile
Since we don't specify versions in our requirements.txt file, I think we need this flag. Otherwise you would get stuck on the latest version as of the initial `make python-venv` run.
Maybe this is not actually needed with the `--ignore-installed` flag, but even if that's true I think it's better to add this explicitly in case we would remove that.
=> chore: update venv deps when installing

.editorconfig, docs/extensions/tutorial.rst, makefile, nix/default.nix, preferences-src/src/components/widgets/ExtensionInstallError.vue, tests/modes/apps/extensions/test_extension_dependencies.py, ulauncher/modes/extensions/extension_controller.py, ulauncher/modes/extensions/extension_dependencies.py, ulauncher/modes/extensions/extension_remote.py, ulauncher/ui/preferences_server.py
#273 
Implements automatic dependency installation for extensions.
Uses `pip install ... --target /path` to download dependencies. Then, it passes the deps dir in `PYTHONPATH` when running extensions.
=> feature: #273 automatically install extensions

flake.lock, nix/default.nix
This PR updates the `webkitgtk` parameter to `webkitgtk_4_1` to align with the changes made to nixpkgs. The previous attribute name `webkitgtk` has been removed from nixpkgs, and using it would result in a build error: "error: 'webkitgtk' attribute has been removed from nixpkgs, use attribute with ABI version set explicitly".
This change fixes the build issue and ensures that the Ulauncher flake can be successfully built with the current version of nixpkgs.
**Changes**:
- Updated `webkitgtk` parameter to `webkitgtk_4_1` in `nix/default.nix`
**Testing**: The build should now succeed with the latest version of nixpkgs. You can verify this by running nix build or nix flake build after applying this PR.
=> Update webkitgtk parameter to webkitgtk_4_1 for compatibility with latest nixpkgs

nix/default.nix
This was never used by us. Wanted to test the ci without it.
=> chore(nix): remove unused dep requests

tests/modes/apps/extensions/test_extension_mode.py, ulauncher/modes/query_handler.py, ulauncher/ui/windows/ulauncher_window.py
Mode handler contains all the stuff that's slow to load. I did previously deferr loading it, but I broke this in recent changes (or maybe in less recent changes too).
Additionally, the event I previously used to load the deferred logic now runs before the window is shows and blocks it from showing. I'm not sure if GTK/Gnome made changes to gazlight me or if this never really worked, but it seems faster in my tests now (loads in ca 80ms on my system, until the window is shown and you can start typing the query).
Also refactored the deferring logic to be more self-contained in the query handler.
=> perf: defer loading mode handler until after UI has loaded

preferences-src/src/components/pages/ExtensionPreferences.vue, tests/modes/apps/extensions/test_extension_remote.py, ulauncher/modes/extensions/extension_controller.py, ulauncher/modes/extensions/extension_remote.py
The major part of this PR is refactoring. After reviewing #1488 I was confused about my own code, and unsure if it was doing the right thing, and I also wanted to simplify the tests so that they would only check the props that are really affected by the tests (otherwise all tests will break if you change any prop). But that lead to a bigger refactoring to make the parse method and result more self contained, ie: handle all parsing and the host, path and id in one place, so the parse result doesn't have to expose internals.
Adds a new "download_url_template" prop so we don't need to conditionally check the host outside of the parser.
Removes the "use_git" prop, which didn't belong in the url parser anyway (I think I put it there, so not blaming anyone else), and now we can check if we have …
=> fix: refactor remote parser and fix url in preferences UI

ulauncher/modes/extensions/extension_socket_server.py
I never touched this, but I can't imagine it's anything other than a leftover from some testing.
This module should never be `__main__`
=> refactor(ext-socket-server): remove logic to start self if __main__

ulauncher/ui/windows/ulauncher_window.py
1. Sets the window to be invisible (opacity=0) initially
2. Moves all the expensive/slow styling and positioning logic to a new method `apply_styling()`, which also removes the opacity=0
3. If not is_composited, runs `apply_styling()` before showing the window (because opacity doesn't work), otherwise wait until after the initial render.
In my profiling it now takes about ~65ms for the window to render and be able to get the keyboard input (~35% speed improvement). This seems to be the last improvement we can do. The rest is almost all GTK internal logic we can't avoid (even if I removed everything from the elements in the window it would only save a couple of ms).
See 7dcb5d9d for reproduction, this also removed migration and kill_ulauncher_v5 scripts since they will be gone some time …
=> perf: defer expensive window operations

makefile
fix: #1527 
Before:
```
find: ‘data/preferences’: No such file or directory
bash: line 12: build: command not found
make: *** [makefile:150: prefs] Error 127
```
After:
```
find: ‘data/preferences’: No such file or directory
yarn is not installed or not executable.
yarn is needed to set up the local build environment.
Please visit https://classic.yarnpkg.com/en/docs/install to install yarn.
make: *** [makefile:150: prefs] Error 1
```
=> fix: check for yarn when running prefs in makefile

ulauncher/modes/extensions/extension_cli_handlers.py, ulauncher/modes/extensions/extension_remote.py
This PR was mostly motivated by needing to change the CLI parser logic before #1543, but it goes further than that.
Leverages `parse_extension_url` to make a simpler method to get the controller, instead of get_argument_type(). Also change the meaning of the controller getter method to only return for installed extensions.
This simplifies our error handling, and aligns with how we've #1543 implements ExtController.
The old error handling was using a lot of try/except with bare excepts, overly verbose errors logged by the modules we're calling from the CLI.
I also did a bunch of testing with network disabled etc, but only for the CLI. I found that the preferences UI extension view also had issues and broken error handling (not introduced in this PR), which needs to be reworked separately.
=> fix(cli): simplify the parsing, ext controller interaction and improve error handling
