data/preferences/index.html, data/preferences/src/components/about-page/about.scss, data/preferences/src/components/general-page/general.scss, data/preferences/src/components/help-page/help.controller.js, data/preferences/src/components/help-page/help.html, data/preferences/src/components/help-page/help.scss, data/preferences/src/components/inputs/ulaunch-input.scss, data/preferences/src/components/main-header/main-header.scss, data/preferences/src/components/main.scss
Issues should be fixed: #31, #32, #34, #36
=> UI Preferences bugs fixing

data/preferences/src/components/main-header/main-header.directive.js, data/preferences/src/components/main-header/main-header.html, data/preferences/src/components/main-header/main-header.scss
+ fixed bug with wrong underlined tab on app. reloading
=> fix #33: Icon and text now hightlighted when mouse is over the tab. 

Dockerfile.build, test, tests/conftest.py, tests/search/calc/test_CalcMode.py, tests/ui/test_ResultItemWidget.py, tests/ui/windows/test_HotkeyDialog.py, tests/ui/windows/test_PreferencesUlauncherDialog.py, ulauncher/search/calc/CalcMode.py, ulauncher/search/calc/CalcResultItem.py
=> Calc fixes

ulauncher/ui/windows/PreferencesUlauncherDialog.py
=> Fixed issue 82: decode unicode strings when saving or updating shortcuts

data/styles/themes/dark/theme-gtk-3.20.css, data/styles/themes/dark/theme.css, data/styles/themes/default-window-styles.css, data/styles/themes/light/theme-gtk-3.20.css, data/styles/themes/light/theme.css, ulauncher/helpers.py, ulauncher/ui/windows/UlauncherWindow.py
=> fixed cursor color and selection color in the input

data/preferences/src/components/pages/Extensions.vue
closes #236
Distro: Linux Mint 19.0
Desktop Environment: Cinnamon 3.8.9
Python version: 2.7.15rc1
=> #236 fix autofocus issue on add extension modal

tests/api/server/test_DeferredResultRenderer.py, ulauncher/api/server/ExtensionController.py, ulauncher/api/shared/event.py
Implements #284 
Criticism is welcome. I'm not a python dev and don't know the Ulauncher internals or your conventions well
Update: Know the tests are broken. Will have a look at this soon
=> Add event.get_keyword_id()

tests/api/server/test_DeferredResultRenderer.py, ulauncher/api/server/ExtensionController.py, ulauncher/api/shared/event.py
Reverts Ulauncher/Ulauncher#287
=> Revert "Add event.get_keyword_id()"

data/preferences/src/components/pages/EditShortcut.vue, tests/search/shortcuts/test_ShortcutResultItem.py, tests/search/shortcuts/test_ShortcutsDb.py, ulauncher/config.py, ulauncher/search/shortcuts/ShortcutResultItem.py, ulauncher/search/shortcuts/ShortcutsDb.py
Implements #191 
You are welcome to make suggestions. I'm not a big Python developer and don't know fully Ulauncher sourcecode.
=> Add feature Run without arguments

data/preferences/src/components/pages/Preferences.vue, ulauncher/main.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/Settings.py, ulauncher/utils/display.py
Closes https://github.com/Ulauncher/Ulauncher/issues/437
Arch Linux
Kernel version 5.3.1
GNOME 3.34
This is my first contribution to a python codebase, so any feedback is welcome :slightly_smiling_face: 
Cheers!
=> Implement option in preferences to set monitor where to render

tests/search/apps/test_AppDb.py, ulauncher/search/apps/AppDb.py
Fixes #18 
* Added app descriptions to the search name
Archlinux MATE Desktop + Compiz
=> Add app descriptions to search

ulauncher/ui/windows/UlauncherWindow.py
Very simple key binding enhancement that fixes #391
=> Tab and shift tab to toggle search results.

ulauncher/api/shared/action/LaunchAppAction.py
Hopefully fixes #754 for good now. It was more complicated than I originally thought as the issue reappeared after the first fix in my fork
* Switch from using `app.launch()` to using subprocess to open all apps, so we can control how they open
* Open with `start_new_session=True`, which prevents child-processes from being killed if you're running the app from the terminal and ctrl+c (SIGINT)
* The above doesn't work when the app is running through systemd, so also test if `systemd-run` exists, and run with that to set a different cgroup (this also fixes the case above, but not if `systemd-run` is missing, which is the reason we need both ways)
* Unrelated to #754 it also properly strips field codes (%f, %F, %u, %U, etc) from the exec line now, which fixes some cases when using custom …
=> Prevent apps from exiting if Ulauncher crashes or is terminated

debian/control, debian/rules
#369 
minor updates to Debianization files
Debian 11 (Bullseye) and MX Linux 21 Beta 1
=> some minor Debianization file updates

ulauncher/api/shared/action/LaunchAppAction.py
This fixes an issue added in my previous PR #812. With that PR, a clean exit from ulauncher isn't possible unless all launched applications are closed. This is because each process had a thread blocked on `os.waitpid()`, which means the threads wouldn't exit until the process they watched exited. For an orderly exit, mostly easily reproduced with a Ctrl-C when running ulauncher from the terminal, things just hanged.
Here I've used GLibs async spawning code because I couldn't find how to ensure children from Python's `subprocess` were reaped without using the waitpid as I was. I considered using `Subprocess.poll` with a sleep, but then I still needed to signal to these threads that they needed to give up, and I needed to make sure the signaling was done in any clean shutdown scenario. This …
=> Use GLib.spawn_async() for app launching to auto-reap children.

scripts/build-release.sh
Added build support for Ubuntu Impish and Bionic
=> Added build support for Ubuntu Impish and Bionic

tests/utils/test_string.py, ulauncher/utils/fuzzy_search.py, ulauncher/utils/string.py
This addresses #708 (avoiding words that would auto close the issue when this gets merged into the dev branch)
=> Strip accents (diacritics) before fuzzy searching

ulauncher/api/shared/action/LaunchAppAction.py
Also, prints a warning each time recommending people not to use systemd if it break for them (assuming they read the log with journalctl)
=> Restore --scope argument but only use systemd-run if running from within a systemd unit

README.md, preferences-src/src/api/fixture.js, preferences-src/src/components/pages/Preferences.vue, ulauncher/config.py, ulauncher/main.py, ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/Settings.py
Implements #802
I tried to make it not require a restart, but unfortunately this didn't work.
=> Move the "--no-window-shadow" CLI setting to a user setting

ulauncher/modes/apps/AppResult.py
Partly solves #270 . Also closes #613. 
Previously discussed on #652
=> Search now also searches app descriptions, albeit with lower priority

ulauncher/api/shared/action/LaunchAppAction.py
=> Support DBusActivatable apps

ulauncher/ui/windows/PreferencesUlauncherDialog.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/ui/windows/WindowHelper.py
Implements #741 and fixes #862
=> Add functionality to drag the main window and Preferences window to move them

ulauncher/api/shared/action/OpenAction.py, ulauncher/modes/apps/launch_app.py, ulauncher/utils/launch_detached.py
=> Make OpenAction launch detached the same way as apps

tests/ui/windows/test_UlauncherWindow.py, ulauncher/ui/windows/UlauncherWindow.py, ulauncher/utils/display.py
Does this look good and work for you @troycurtisjr? I can probably test this myself later, but I at least wasn't initially able to get the same issue as you did.
=> Simplify Display utilities and switch from deprecated APIs (GTK 3.22+)

tests/modes/calc/test_CalcMode.py, ulauncher/modes/calc/CalcMode.py
I don't know if someone else need this, but sometimes I need to calculate modulus, so for me this addition is very useful.
By the way, I'm not very good with regex, so I'm not sure if the way I did it is the best.
https://user-images.githubusercontent.com/57065994/160296463-5dbb5cb0-6097-4885-a319-d6f100767c45.mp4
=> Add mod operator support

ulauncher/modes/extensions/ExtensionRemote.py
Fixes #579
This adds GitLab support to the extension remote class so extension developers can host extensions on gitlab.com.
Can be tested with https://gitlab.com/friday/ulauncher-locate
Self-hosted isn't supported. It's assumed that any domain other than github.com and gitlab.com is gitea-compatible. Might revisit this logic later.
Also see #1024
=> Add support for extensios hosted on GitLab.com

preferences-src/src/components/pages/EditShortcut.vue, preferences-src/src/components/pages/Shortcuts.vue
=> Use monospaced fonts in shortcut query field

ulauncher/modes/apps/launch_app.py
=> Only check for SingleMainWindow on X11

ulauncher/api/extension.py
Use a new thread for each extension event listener invocation to avoid blocking the main extension thread. See #1112
=> Extension client: Use a new thread for each extension event listener invocation

docs/extensions/tutorial.rst
https://docs.npmjs.com/misc/semver results in 404.
=> Fix broken npm semver link

debian/control
=> Addes zstd to deal with control.tar.zst

ulauncher/modes/apps/AppResult.py
This adds or removes 5% weight for the search results based on how often they have been launched before.
It's only for apps, since we only have this data for apps.
I never actually tested any other value. 5% in both directions seems good enough.
See #742 and https://github.com/Ulauncher/Ulauncher/pull/742#issuecomment-903257595
=> feat(search): weight apps by launch count

io.ulauncher.Ulauncher.service
simple change to make it easier to replace paths in #1307
=> use /usr/bin/ulauncher contistently with systemd service

setup.py
mostly related to Nix ways of doing things (symlinks everything that can be symlinked), but doesn't break anything for general use-case.
picked off #1307
=> chore(setup): make data_files_from_path() symlink-aware

.github/workflows/tests.yml, CONTRIBUTING.md, bin/ulauncher, flake.lock, makefile, nix/default.nix, pyproject.toml, ul
=> remove ul, update, cleanup & fix Nix code

nix/default.nix
I don't know anything about this, but I got notified by that this was needed to fix the flake :D
=> fix: fix nix flake

.github/workflows/tests.yml, flake.lock
Fix for the build that was missing the flake update
=> Update flake 05.02.2025

.github/workflows/draft-release.yml, .github/workflows/publish-release.yml, .github/workflows/tests.yml, .vscode/settings.json, CONTRIBUTING.md, Dockerfile, README.md, makefile, requirements.txt, ulauncher/utils/wm.py
- removed deprecated config properties from `.vscode/settings.json`
- added `make python-venv` that simplifies local env setup. Now IDE correctly reads Gkt, Gdk imports!
- simplified dev env instructions in CONTRIBUTING.md
=> chore: improved python env setup, fixed mypy errors

ulauncher/cli.py, ulauncher/main.py, ulauncher/modes/extensions/extension_cli_handlers.py, ulauncher/modes/extensions/extension_controller.py, ulauncher/modes/extensions/extension_socket_server.py
#1150
I will extract logger config in a separate PR. I also want to add a bit of color to the logs and remove unnecessary logs (such as `Using selector...`)
=> feat: basic CLI for extension management

.github/workflows/draft-release.yml, .github/workflows/publish-release.yml, .github/workflows/tests.yml
Update checkout action and use double quotation marks (some linter I didn't know I had did that for me)
=> chore: update git checkout action

ulauncher/modes/apps/app_mode.py, ulauncher/modes/apps/app_result.py, ulauncher/utils/desktopappinfo.py
Wrap DesktopAppInfo to fix broken unbound instance methods
Fixes #1550
=> fix: add wrapper for broken Glib system dependencies on debian forky
